/** Cross-site duplication remediation (AdSense doorway/scaled-content
 *  policy, Phase C) -- recipes, media reviews, and the science column
 *  read near-identical across all three towns despite being generated by
 *  SEPARATE per-town AI calls (see ai_pipeline/daily_content.py's own
 *  per-town local_input), because the underlying topic (a weekday dinner,
 *  a movie currently in theaters, a science story) usually isn't
 *  inherently local -- there's rarely enough town-specific material for
 *  the model to diverge on. Canonical consolidation (cheapest of the two
 *  options in the handoff, no extra generation cost) rather than
 *  regenerating per-town variation.
 *
 *  scheduler/weekly_rotation.py's ROTATION is a single, fixed day-of-week
 *  schedule -- confirmed live: every town runs daily_content.py against
 *  the SAME `content_type_for(date)` on the SAME calendar day, and story
 *  slugs for these types are date-only ("vetenskap_kronika-2026-08-28"),
 *  never town-scoped (unlike their image filenames, which ARE town-scoped
 *  -- see images.ts). That means the exact same slug exists on all three
 *  domains for the same day's rotation entry, so the origin's canonical
 *  URL can be constructed by swapping domains on the SAME slug -- no
 *  cross-town lookup or DB query needed at build time.
 *
 *  Rotated one content type per town (not one town for everything) so no
 *  single site reads as a pure mirror of another. */
import type { SourceType } from './db';
import { ALL_SITES } from './site-config';

export const CROSS_SITE_CANONICAL_ORIGINS: Partial<Record<SourceType, string>> = {
  vardagsmiddag: 'brookings_sd',
  media_recension: 'moreno_valley_ca',
  vetenskap_kronika: 'broomfield_co',
};

/** Front-page demotion handoff ("demote shared content from the feature
 *  slot"): this map is ALREADY the single source of truth this codebase
 *  has for "which content-track types are shared, town-agnostic topics
 *  rather than genuinely local material" -- that's exactly why Phase C
 *  uses it to pick one canonical origin per type in the first place. The
 *  front page reuses it for a second, independent purpose (placement:
 *  `feature` slot vs the compact "More to read" row) rather than adding a
 *  second shared/unique flag that could drift from this one. Every
 *  content-track type NOT in CROSS_SITE_CANONICAL_ORIGINS (editorial,
 *  culture_essay, kvick_essa) is "local" by the same logic: there was
 *  never enough town-specific material in the shared ones for the model to
 *  diverge on, which is precisely why they needed a canonical origin at
 *  all -- the other three didn't. */
export function isSharedContentType(sourceType: SourceType): boolean {
  return sourceType in CROSS_SITE_CANONICAL_ORIGINS;
}

/** Plain array form of CROSS_SITE_CANONICAL_ORIGINS' keys, for SQL `= ANY(...)`
 *  filters (lib/db.ts's getRecentCompactContent()) that need a real string
 *  array rather than a lookup function. */
export const SHARED_CONTENT_SOURCE_TYPES: SourceType[] =
  Object.keys(CROSS_SITE_CANONICAL_ORIGINS) as SourceType[];

/**
 * Returns the canonical URL to use for this story: the normal self-URL if
 * this story's type isn't cross-site-shared, or if this very town IS the
 * designated origin for it; otherwise the origin town's URL for the exact
 * same slug. Never returns null/undefined -- every story has SOME
 * canonical URL, self or cross.
 */
export function canonicalUrlForStory(
  sourceType: SourceType,
  slug: string,
  currentTownId: string,
  selfUrl: string,
): string {
  const originTownId = CROSS_SITE_CANONICAL_ORIGINS[sourceType];
  if (!originTownId || originTownId === currentTownId) return selfUrl;

  const origin = ALL_SITES.find((s) => s.townId === originTownId);
  if (!origin) return selfUrl; // defensive only -- every real townId is in ALL_SITES

  return new URL(`/s/${slug}/`, origin.siteUrl).href;
}
