/**
 * Per-town, per-category REAL photos for lib/images.ts's resolveImage()
 * tier 3 -- see NEEDS-HUMAN-REVIEW.md, "Switch venue/category images to
 * real photos". Generated by scripts/source_category_images.py -- edit the
 * query/selection there and re-run to change one image, don't hand-edit
 * paths here. Town entries not in this script's own CATEGORY_SEARCHES are
 * preserved verbatim, not deleted (see _write_category_images_ts()).
 */
import type { ImageCategory, ImageRef } from '../lib/images';

export type Town = 'brookings_sd' | 'moreno_valley_ca' | 'broomfield_co';

export const CATEGORY_IMAGES: Record<Town, Partial<Record<ImageCategory, ImageRef>>> = {
  brookings_sd: {
    city_hall: { path: '/assets/images/categories/brookings_sd-city_hall.png', alt: 'Civic buildings in Brookings.', width: 1200, height: 800, attributionText: 'Photo by Phil Evenden on Pexels', attributionUrl: 'https://www.pexels.com/@philevenphotos' },
    events: { path: '/assets/images/categories/brookings_sd-events.png', alt: 'Community events in Brookings.', width: 1200, height: 800, attributionText: 'Photo by Tom Fisk on Pexels', attributionUrl: 'https://www.pexels.com/@tomfisk' },
    home_sales: { path: '/assets/images/categories/brookings_sd-home_sales.png', alt: 'Residential homes in Brookings.', width: 1200, height: 800, attributionText: 'Photo by David McBee on Pexels', attributionUrl: 'https://www.pexels.com/@davidmcbee' },
    jobs: { path: '/assets/images/categories/brookings_sd-jobs.png', alt: 'Local employers in Brookings.', width: 1200, height: 800, attributionText: 'Photo by Quang Vuong on Pexels', attributionUrl: 'https://www.pexels.com/@quang-vuong-724225078' },
    school_alerts: { path: '/assets/images/categories/brookings_sd-school_alerts.png', alt: 'Schools in Brookings.', width: 1200, height: 800, attributionText: 'Photo by Caleb Oquendo on Pexels', attributionUrl: 'https://www.pexels.com/@caleboquendo' },
    sports: { path: '/assets/images/categories/brookings_sd-sports.png', alt: 'Jackrabbits and regional sports in Brookings.', width: 1200, height: 800, attributionText: 'Photo by Yura Forrat on Pexels', attributionUrl: 'https://www.pexels.com/@yuraforrat' },
    university: { path: '/assets/images/categories/brookings_sd-university.png', alt: 'South Dakota State University in Brookings.', width: 1200, height: 800, attributionText: 'Photo by Chris F on Pexels', attributionUrl: 'https://www.pexels.com/@chris-f-38966' },
    weather_alert: { path: '/assets/images/categories/brookings_sd-weather_alert.png', alt: 'Weather conditions in Brookings.', width: 1200, height: 800, attributionText: 'Photo by Matt W on Pexels', attributionUrl: 'https://www.pexels.com/@matt-w-701415160' },
  },
  moreno_valley_ca: {
    city_hall: { path: '/assets/images/categories/moreno_valley_ca-city_hall.png', alt: 'Civic buildings in Moreno Valley.', width: 1200, height: 800, attributionText: 'Photo by Mark Direen on Pexels', attributionUrl: 'https://www.pexels.com/@mark-direen-622749' },
    events: { path: '/assets/images/categories/moreno_valley_ca-events.png', alt: 'Community events in Moreno Valley.', width: 1200, height: 800, attributionText: 'Photo by Tony  Wu on Pexels', attributionUrl: 'https://www.pexels.com/@tonywuphotography' },
    home_sales: { path: '/assets/images/categories/moreno_valley_ca-home_sales.png', alt: 'Residential homes in Moreno Valley.', width: 1200, height: 800, attributionText: 'Photo by Robert So on Pexels', attributionUrl: 'https://www.pexels.com/@robertkso' },
    jobs: { path: '/assets/images/categories/moreno_valley_ca-jobs.png', alt: 'Warehouse and logistics employers in Moreno Valley.', width: 1200, height: 800, attributionText: 'Photo by Peter Xie on Pexels', attributionUrl: 'https://www.pexels.com/@peter-xie-371876898' },
    school_alerts: { path: '/assets/images/categories/moreno_valley_ca-school_alerts.png', alt: 'Schools in Moreno Valley.', width: 1200, height: 800, attributionText: 'Photo by RDNE Stock project on Pexels', attributionUrl: 'https://www.pexels.com/@rdne' },
    sports: { path: '/assets/images/categories/moreno_valley_ca-sports.png', alt: 'Regional sports in the Moreno Valley area.', width: 1200, height: 800, attributionText: 'Photo by Yura Forrat on Pexels', attributionUrl: 'https://www.pexels.com/@yuraforrat' },
    traffic: { path: '/assets/images/categories/moreno_valley_ca-traffic.png', alt: 'Freeway traffic in Moreno Valley.', width: 1200, height: 800, attributionText: 'Photo by RDNE Stock project on Pexels', attributionUrl: 'https://www.pexels.com/@rdne' },
    weather_alert: { path: '/assets/images/categories/moreno_valley_ca-weather_alert.png', alt: 'Weather conditions in Moreno Valley.', width: 1200, height: 800, attributionText: 'Photo by Tom Fournier on Pexels', attributionUrl: 'https://www.pexels.com/@tom-fournier-208942721' },
    workplace_watch: { path: '/assets/images/categories/moreno_valley_ca-workplace_watch.png', alt: 'Warehouse and logistics workplaces in Moreno Valley.', width: 1200, height: 800, attributionText: 'Photo by Giant Asparagus on Pexels', attributionUrl: 'https://www.pexels.com/@giantasparagus' },
  },

  broomfield_co: {},
};

/** Safe lookup for a town with no CATEGORY_IMAGES entry at all (e.g. a
 *  newly-added town before its images are generated) -- every call site
 *  used to index CATEGORY_IMAGES[townId] directly with no fallback, which
 *  is `undefined` for an unlisted key and crashes resolveImage() with a
 *  raw TypeError (`undefined[category]`) instead of degrading to "no
 *  image" the way the rest of that function is designed to. */
export function categoryImagesFor(townId: string): Partial<Record<ImageCategory, ImageRef>> {
  return CATEGORY_IMAGES[townId as Town] ?? {};
}
