/**
 * Per-town, per-category illustrations for lib/images.ts's resolveImage()
 * tier 3 -- see NEEDS-HUMAN-REVIEW.md, "Venue & Category Image Identity".
 * Generated by scripts/generate_venue_category_images.py -- edit the motif
 * there and re-run to regenerate a single image, don't hand-edit paths here.
 * Town entries NOT in this script's own motif dicts (e.g. a newly-added
 * town with no images yet) are preserved verbatim, not deleted -- see
 * _preserve_unmanaged_content().
 */
import type { ImageCategory, ImageRef } from '../lib/images';

export type Town = 'brookings_sd' | 'moreno_valley_ca' | 'broomfield_co';

export const CATEGORY_IMAGES: Record<Town, Partial<Record<ImageCategory, ImageRef>>> = {
  brookings_sd: {
    city_hall: { path: '/assets/images/categories/brookings_sd-city_hall.png', alt: 'Civic buildings in Brookings.', width: 1200, height: 800 },
    events: { path: '/assets/images/categories/brookings_sd-events.png', alt: 'Community events in Brookings.', width: 1200, height: 800 },
    home_sales: { path: '/assets/images/categories/brookings_sd-home_sales.png', alt: 'Residential homes in Brookings.', width: 1200, height: 800 },
    jobs: { path: '/assets/images/categories/brookings_sd-jobs.png', alt: 'Local employers in Brookings.', width: 1200, height: 800 },
    school_alerts: { path: '/assets/images/categories/brookings_sd-school_alerts.png', alt: 'Schools in Brookings.', width: 1200, height: 800 },
    sports: { path: '/assets/images/categories/brookings_sd-sports.png', alt: 'Jackrabbits and regional sports in Brookings.', width: 1200, height: 800 },
    university: { path: '/assets/images/categories/brookings_sd-university.png', alt: 'South Dakota State University in Brookings.', width: 1200, height: 800 },
    weather_alert: { path: '/assets/images/categories/brookings_sd-weather_alert.png', alt: 'Weather conditions in Brookings.', width: 1200, height: 800 },
  },
  moreno_valley_ca: {
    city_hall: { path: '/assets/images/categories/moreno_valley_ca-city_hall.png', alt: 'Civic buildings in Moreno Valley.', width: 1200, height: 800 },
    events: { path: '/assets/images/categories/moreno_valley_ca-events.png', alt: 'Community events in Moreno Valley.', width: 1200, height: 800 },
    home_sales: { path: '/assets/images/categories/moreno_valley_ca-home_sales.png', alt: 'Residential homes in Moreno Valley.', width: 1200, height: 800 },
    jobs: { path: '/assets/images/categories/moreno_valley_ca-jobs.png', alt: 'Warehouse and logistics employers in Moreno Valley.', width: 1200, height: 800 },
    school_alerts: { path: '/assets/images/categories/moreno_valley_ca-school_alerts.png', alt: 'Schools in Moreno Valley.', width: 1200, height: 800 },
    sports: { path: '/assets/images/categories/moreno_valley_ca-sports.png', alt: 'Regional sports in the Moreno Valley area.', width: 1200, height: 800 },
    traffic: { path: '/assets/images/categories/moreno_valley_ca-traffic.png', alt: 'Freeway traffic in Moreno Valley.', width: 1200, height: 800 },
    weather_alert: { path: '/assets/images/categories/moreno_valley_ca-weather_alert.png', alt: 'Weather conditions in Moreno Valley.', width: 1200, height: 800 },
    workplace_watch: { path: '/assets/images/categories/moreno_valley_ca-workplace_watch.png', alt: 'Warehouse and logistics workplaces in Moreno Valley.', width: 1200, height: 800 },
  },

  broomfield_co: {},
};

/** Safe lookup for a town with no CATEGORY_IMAGES entry at all (e.g. a
 *  newly-added town before its images are generated) -- every call site
 *  used to index CATEGORY_IMAGES[townId] directly with no fallback, which
 *  is `undefined` for an unlisted key and crashes resolveImage() with a
 *  raw TypeError (`undefined[category]`) instead of degrading to "no
 *  image" the way the rest of that function is designed to. */
export function categoryImagesFor(townId: string): Partial<Record<ImageCategory, ImageRef>> {
  return CATEGORY_IMAGES[townId as Town] ?? {};
}
