"""Retroactive, READ-ONLY per-town event source-share report -- Fas 3 del 1
(event source registry refactor) balance guardrail.

Before this script existed, a source-imbalance like "one library calendar
is 71% of all events shown on /events" (Moreno Valley) was only ever found
by someone manually running a GROUP BY -- see the handoff brief that
prompted this whole registry refactor. This makes that check a standing,
one-command report instead, so a NEW imbalance (a future source going
quiet, or a new source launching lopsided) surfaces proactively.

Which `events.source` values count as "community events" for the
denominator is read from each town's own `configs/<town_id>.json`
`data_sources.events.sources[]` list -- config-driven, not a hardcoded
name check. Rows whose `source` isn't in that list (nws_alert,
county_alert -- written into the same `events` table by unrelated parsers,
see db/schema.sql) are reported separately, not folded into the share
calculation, since they're not part of what a reader sees as "this week's
events" in the first place.

Does NOT unpublish, edit, or delete anything. Writes
EVENT_SOURCE_SHARE_REPORT.md at the repo root.

Usage:
    python -m scripts.event_source_share
    python -m scripts.event_source_share --town moreno_valley_ca
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from ai_pipeline.town_guard import ALL_TOWN_IDS
from db.db import get_conn

# Above this share, a single source is flagged as dominant -- not an error,
# just the proactive signal the task asked for (today's known cases,
# Brookings library ~58%/Moreno Valley library ~71%, are BOTH expected to
# trip this; that's the sanity check that the report works, not a bug).
DOMINANCE_THRESHOLD = 0.5


def _load_config(town_id: str) -> dict:
    return json.loads(Path(f"configs/{town_id}.json").read_text(encoding="utf-8"))


def _configured_sources(cfg: dict) -> dict[str, str]:
    """name -> kind, for every entry in this town's events.sources[] (empty
    for a town whose events config has no sources[] array at all -- e.g.
    Broomfield's flat WebTrac shape, see event_sources.py's own docstring
    for why that shape needed this registry in the first place)."""
    events_cfg = cfg.get("data_sources", {}).get("events", {})
    return {src["name"]: src.get("kind", "?") for src in events_cfg.get("sources", [])}


def _counts_by_source(conn, town_id: str) -> dict[str, int]:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT source, count(*) FROM events WHERE town_id = %s GROUP BY source",
            (town_id,),
        )
        return {row[0]: row[1] for row in cur.fetchall()}


def build_town_report(conn, town_id: str) -> dict:
    cfg = _load_config(town_id)
    configured = _configured_sources(cfg)
    counts = _counts_by_source(conn, town_id)

    community = {name: counts.get(name, 0) for name in configured}
    other = {name: n for name, n in counts.items() if name not in configured}

    total = sum(community.values())
    shares = []
    for name, count in sorted(community.items(), key=lambda kv: -kv[1]):
        share = (count / total) if total else 0.0
        shares.append({
            "name": name, "kind": configured[name], "count": count,
            "share": share, "dominant": share > DOMINANCE_THRESHOLD,
        })

    return {
        "town_id": town_id, "total_community_events": total,
        "sources": shares, "excluded_non_community": other,
    }


def render_report(reports: list[dict]) -> str:
    lines = [
        "# Event source-share report",
        "",
        "Generated by `scripts/event_source_share.py` (read-only). Share is "
        "computed over each town's configured community-event sources "
        "(`data_sources.events.sources[]`) only -- see module docstring for "
        "why other `events.source` values (weather/county alerts) are "
        f"excluded. A source above {DOMINANCE_THRESHOLD:.0%} of a town's "
        "events is flagged `dominant`, a proactive signal, not an error.",
        "",
    ]
    for r in reports:
        lines.append(f"## {r['town_id']} ({r['total_community_events']} community events)")
        lines.append("")
        if not r["sources"]:
            lines.append("No configured event sources for this town.")
            lines.append("")
            continue
        lines.append("| source | kind | count | share | |")
        lines.append("|---|---|---:|---:|---|")
        for s in r["sources"]:
            flag = "**dominant**" if s["dominant"] else ""
            lines.append(f"| {s['name']} | {s['kind']} | {s['count']} | {s['share']:.0%} | {flag} |")
        lines.append("")
        if r["excluded_non_community"]:
            excluded = ", ".join(f"{n} ({c})" for n, c in r["excluded_non_community"].items())
            lines.append(f"_Excluded (non-community-event rows in the same table): {excluded}_")
            lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--town", choices=ALL_TOWN_IDS, help="report only this town (default: all)")
    args = ap.parse_args()

    towns = [args.town] if args.town else ALL_TOWN_IDS

    reports = []
    with get_conn() as conn:
        for town_id in towns:
            print(f"Computing source share for {town_id}...")
            report = build_town_report(conn, town_id)
            reports.append(report)
            for s in report["sources"]:
                flag = " <- DOMINANT" if s["dominant"] else ""
                print(f"  {s['name']:<24} {s['count']:>5}  {s['share']:.0%}{flag}")

    Path("EVENT_SOURCE_SHARE_REPORT.md").write_text(render_report(reports), encoding="utf-8")
    print("\nWrote EVENT_SOURCE_SHARE_REPORT.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
