"""Retroactive, READ-ONLY scan of already-published `stories` for cross-site
(Brookings <-> Moreno Valley) contamination -- see ai_pipeline/town_guard.py
for the shared blocklists and the root-cause writeup (a hardcoded-town-name
bug in content/*.py, fixed 2026-08-07 in a5ebec0/e108341).

This script does NOT unpublish, edit, or delete anything. It produces
CONTAMINATION_REPORT.md at the repo root: every flagged row, the matched
term(s) in context, a tier (hard/review), and a recommended action --
`unpublish` / `relocate to sister site` / `rewrite locally` / `false
positive` -- for a human to act on. See NEEDS-HUMAN-REVIEW.md.

Usage:
    python -m scripts.scan_contamination
    python -m scripts.scan_contamination --town moreno_valley_ca
"""
from __future__ import annotations

import argparse
import textwrap

from ai_pipeline.town_guard import (
    ALL_TOWN_IDS, HARD_BLOCKLIST, REVIEW_BLOCKLIST, addressed_reader_hits,
    validate_town_identity,
)
from db.db import get_conn


def gather_stories(conn, town_id: str) -> list[dict]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT slug, title, body, source_type, published_at
              FROM stories
             WHERE town_id = %s
             ORDER BY published_at
            """,
            (town_id,),
        )
        cols = [d.name for d in cur.description]
        return [dict(zip(cols, row)) for row in cur.fetchall()]


def excerpt(text: str, term: str, context: int = 60) -> str:
    low = text.casefold()
    idx = low.find(term.casefold())
    if idx == -1:
        return ""
    start = max(0, idx - context)
    end = min(len(text), idx + len(term) + context)
    snippet = text[start:end].replace("\n", " ")
    prefix = "…" if start > 0 else ""
    suffix = "…" if end < len(text) else ""
    return f"{prefix}{snippet}{suffix}"


def recommend_action(hard_hits: list[str], escalated: list[str]) -> str:
    """Best-effort pre-sort, not a final decision -- see module docstring."""
    if not hard_hits:
        return "false positive"  # only review-tier hits, or nothing hard
    if escalated:
        # A hard term appeared next to an "addressed reader" marker --
        # the piece talks TO the other town, not just ABOUT it.
        return "rewrite locally"
    return "relocate to sister site"


def scan_town(conn, town_id: str) -> list[dict]:
    rows = gather_stories(conn, town_id)
    flagged = []
    for row in rows:
        full_text = f"{row['title']}\n\n{row['body']}"
        gate = validate_town_identity(full_text, town_id)
        if gate.passed and not gate.reviews:
            continue

        hard_terms = [v.split(": ", 1)[1] for v in gate.violations]
        review_terms = [v.split(": ", 1)[1] for v in gate.reviews]
        escalated = addressed_reader_hits(full_text, hard_terms)

        flagged.append({
            "town_id": town_id,
            "slug": row["slug"],
            "source_type": row["source_type"],
            "published_at": row["published_at"],
            "hard_terms": hard_terms,
            "review_terms": review_terms,
            "escalated": escalated,
            "excerpts": {t: excerpt(full_text, t) for t in (hard_terms + review_terms)},
            "recommended_action": recommend_action(hard_terms, escalated),
        })
    return flagged


def render_report(all_flagged: dict[str, list[dict]]) -> str:
    lines = [
        "# Contamination scan report",
        "",
        "Generated by `scripts/scan_contamination.py` (read-only -- nothing here has "
        "been unpublished). Every row is a recommendation, not a decision -- a human "
        "makes the final call per item. See NEEDS-HUMAN-REVIEW.md.",
        "",
    ]
    total = sum(len(v) for v in all_flagged.values())
    lines.append(f"**Total flagged rows: {total}**")
    lines.append("")

    for town_id in ALL_TOWN_IDS:
        flagged = all_flagged.get(town_id, [])
        lines.append(f"## {town_id} ({len(flagged)} flagged)")
        lines.append("")
        if not flagged:
            lines.append("Nothing flagged.")
            lines.append("")
            continue
        for item in flagged:
            lines.append(f"### `/s/{item['slug']}` — {item['source_type']}, "
                         f"published {item['published_at']}")
            lines.append(f"**Recommended action:** `{item['recommended_action']}`")
            if item["hard_terms"]:
                lines.append(f"- Hard-blocklist terms: {', '.join(item['hard_terms'])}")
            if item["review_terms"]:
                lines.append(f"- Review-tier terms: {', '.join(item['review_terms'])}")
            if item["escalated"]:
                lines.append(
                    f"- Addressed-reader escalation (appears with \"here in\"/\"our own\"/"
                    f"etc.): {', '.join(item['escalated'])}"
                )
            for term, snippet in item["excerpts"].items():
                if snippet:
                    lines.append(f"  - `{term}`: {textwrap.shorten(snippet, 200)}")
            lines.append("")

    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--town", choices=ALL_TOWN_IDS, help="scan only this town (default: both)")
    args = ap.parse_args()

    towns = [args.town] if args.town else ALL_TOWN_IDS

    all_flagged: dict[str, list[dict]] = {}
    with get_conn() as conn:
        for town_id in towns:
            print(f"Scanning {town_id}...")
            flagged = scan_town(conn, town_id)
            all_flagged[town_id] = flagged
            print(f"  {len(flagged)} flagged")

    report = render_report(all_flagged)
    with open("CONTAMINATION_REPORT.md", "w", encoding="utf-8") as f:
        f.write(report)
    print("\nWrote CONTAMINATION_REPORT.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
